apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-media-generation-service-config
  labels:
    app: ai-media-generation-service-config
data:
  PORT: ""
  ENV: ""
  LOG_LEVEL: ""
  NATS_URL: ""
  NATS_STREAM: ""
  COMFYUI_URL: ""
  S3_ENDPOINT_URL: ""
  S3_BUCKET: ""
